spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wordpress?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8086
  servlet:
    context-path: /wp-json/wp/v2